clear;

% Load in the data structures: M & S.
load('TLPmap_uk.mat');
load('TLP_uk.mat');

% Load in the country boundary shapefiles.
ShapeFilename1='/Users/rjs10/Desktop/TLPuk/data/Outlines/GBR_adm/GBR_adm0.shp';
ShapeFilename2='/Users/rjs10/Desktop/TLPuk/data/Outlines/IRL_adm/IRL_adm0.shp';
C1=shaperead(ShapeFilename1);
C2=shaperead(ShapeFilename2);

% Predefine some variables.
GREY=[0.85,0.85,0.85];
lat=linspace(min(S.MAP.latB),max(S.MAP.latB),7); lat(2:end-1);
lon=linspace(min(S.MAP.lonB),max(S.MAP.lonB),7); lon(2:end-1);
[~,m]=min(Geoid_Distance(lat(1),lon(1),[S.RISK.lat],[S.RISK.lon],'spherical'));
[~,i]=min(Geoid_Distance(lat(2),lon(2),[S.RISK.lat],[S.RISK.lon],'spherical'));
[~,j]=min(Geoid_Distance(lat(3),lon(3),[S.RISK.lat],[S.RISK.lon],'spherical'));
[~,k]=min(Geoid_Distance(lat(4),lon(4),[S.RISK.lat],[S.RISK.lon],'spherical'));
[~,l]=min(Geoid_Distance(lat(5),lon(5),[S.RISK.lat],[S.RISK.lon],'spherical'));
Nv=length(S.dVAR.b);
yl=[7e-2 7e+5];
ML_c=[1.0 4.0];

% Get boundaries of play area.
YL=[min(S.MAP.latB)-0.1 max(S.MAP.latB)+0.1];
XL=[min(S.MAP.lonB)-0.1 max(S.MAP.lonB)+0.1];

% Plot all map data.
figure(1); clf;
subplot(411);
contourf(S.MAP.lonG,S.MAP.latG,S.MAP.Vs30,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
plot(S.RISK(m).lon,S.RISK(m).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(i).lon,S.RISK(i).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(j).lon,S.RISK(j).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(k).lon,S.RISK(k).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(l).lon,S.RISK(l).lat,'wo','MarkerFaceColor','k');
xlabel('Longitude'); ylabel('Latitude'); title('Site Amplification');
h = colorbar(); colormap(gca,R_colormap('Vs30')); ylabel(h, 'Site Amplififcation, Vs30 (m/s)'); hold off;
subplot(412);
contourf(S.MAP.lonE,S.MAP.latE,S.MAP.DEP,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
plot(S.RISK(m).lon,S.RISK(m).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(i).lon,S.RISK(i).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(j).lon,S.RISK(j).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(k).lon,S.RISK(k).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(l).lon,S.RISK(l).lat,'wo','MarkerFaceColor','k');
xlabel('Longitude'); ylabel('Latitude'); title('Formation Depth');
h = colorbar(); colormap(gca,R_colormap('Depth')); ylabel(h, 'True Vertical Depth (km)'); hold off;
subplot(413);
contourf(S.MAP.lonG,S.MAP.latG,log10(S.MAP.POP),'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-w');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
plot(S.RISK(m).lon,S.RISK(m).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(i).lon,S.RISK(i).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(j).lon,S.RISK(j).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(k).lon,S.RISK(k).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(l).lon,S.RISK(l).lat,'wo','MarkerFaceColor','k');
set(gca,'Color','k');
xlabel('Longitude'); ylabel('Latitude'); title(['Population (',sprintf('%0.3g',sum(sum(S.MAP.POP))),')']);
h = colorbar(); colormap(gca,R_colormap('population')); ylabel(h, 'Population (log_{10}[people])'); hold off;
subplot(414);
contourf(S.MAP.lonE,S.MAP.latE,S.MAP.Ir,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
plot(S.RISK(m).lon,S.RISK(m).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(i).lon,S.RISK(i).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(j).lon,S.RISK(j).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(k).lon,S.RISK(k).lat,'wo','MarkerFaceColor','k');
plot(S.RISK(l).lon,S.RISK(l).lat,'wo','MarkerFaceColor','k');
xlabel('Longitude'); ylabel('Latitude'); colorbar(); colormap(gca,'default'); title('In Bounds'); hold off;

% Plot all perturbation data.
figure(2); clf;
subplot(3,4,1); histogram(S.dVAR.dZ, round(sqrt(Nv)) );
xlabel('Depth Perturbation, dZ (km)'); ylabel('Count');
subplot(3,4,2); histogram(S.dVAR.b, round(sqrt(Nv)) );
xlabel('b-value distribution, b (-)'); ylabel('Count');
subplot(3,4,3); histogram(S.dVAR.dM, round(sqrt(Nv)) );
xlabel('Magnitude Perturbation, dM (Mw)'); ylabel('Count');
set(gca, 'YScale', 'log');
subplot(3,4,4); histogram(S.dVAR.dGM, round(sqrt(Nv)) );
xlabel('GMPE Perturbation, dGM (-)'); ylabel('Count');
subplot(3,4,5); histogram(S.dVAR.dN1, round(sqrt(Nv)) );
xlabel('Nuisance Fxn Perturbation, dN1 (-)'); ylabel('Count');
subplot(3,4,6); histogram(S.dVAR.dN2, round(sqrt(Nv)) );
xlabel('Nuisance Fxn Perturbation, dN2 (-)'); ylabel('Count');
subplot(3,4,7); histogram(S.dVAR.Po, round(sqrt(Nv)) );
xlabel('Damage Fxn Initial Damage State, \Psi_o (-)'); ylabel('Count');
subplot(3,4,8); histogram(S.dVAR.dLPR, round(sqrt(Nv)) );
xlabel('LPR Vulnerability Fxn Perturbation, dLPRP (-)'); ylabel('Count');
subplot(3,4,9); histogram(S.dVAR.dSA, round(sqrt(Nv)) );
xlabel('Site Amp Perturbation, dSA (-)'); ylabel('Count');
subplot(3,4,10); histogram(S.dVAR.dPOP, round(sqrt(Nv)) );
xlabel('Population Perturbation Factor, dPOP (-)'); ylabel('Count');

% Plot some of the count curves.
figure(3); clf;
subplot(4,3,1);
semilogy(S.Mw,S.RISK(i).Nn2,'-','color',GREY); hold on;
semilogy(S.Mw,mean(S.RISK(i).Nn2,1),'-r');
semilogy(S.Mw,median(S.RISK(i).Nn2,1),'-b');
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Nuisance: CDI 2');
ylim(yl);
subplot(4,3,2);
semilogy(S.Mw,S.RISK(i).Nd1,'-','color',GREY); hold on;
semilogy(S.Mw,mean(S.RISK(i).Nd1,1),'-r');
semilogy(S.Mw,median(S.RISK(i).Nd1,1),'-b');
line(xlim(),M.D.T1*[1 1],'Color','k','LineStyle','--');
line(M.D.Tm*[1 1],ylim(), 'Color','k','LineStyle','--');
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Damage: DS 1');
ylim(yl);
subplot(4,3,3);
semilogy(S.Mw,S.RISK(i).Pf1,'-','color',GREY); hold on;
semilogy(S.Mw,mean(S.RISK(i).Pf1,1),'-r');
semilogy(S.Mw,median(S.RISK(i).Pf1,1),'-b');
line(xlim(),M.R.T1*[1 1],'Color','k','LineStyle','--');
line(M.R.Tm*[1 1],ylim(), 'Color','k','LineStyle','--');
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Probability of Loss of Life'); title('LPR: Fatality');
ylim([1e-7 1e0]);
subplot(4,3,4);
semilogy(S.Mw,S.RISK(i).Nn3,'-','color',GREY); hold on;
semilogy(S.Mw,mean(S.RISK(i).Nn3,1),'-r');
semilogy(S.Mw,median(S.RISK(i).Nn3,1),'-b');
line(xlim(),M.N.T3*[1 1],'Color','k','LineStyle','--');
line(M.N.Tm*[1 1],ylim(), 'Color','k','LineStyle','--');
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Nuisance: CDI 3');
ylim(yl);
subplot(4,3,5);
semilogy(S.Mw,S.RISK(i).Nd2,'-','color',GREY); hold on;
semilogy(S.Mw,mean(S.RISK(i).Nd2,1),'-r');
semilogy(S.Mw,median(S.RISK(i).Nd2,1),'-b');
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Damage: DS 2');
ylim(yl);
subplot(4,3,[7 10]);
semilogy(S.Mw,median(S.RISK(i).Nn2,1),'DisplayName','CDI 2'); hold on;
semilogy(S.Mw,median(S.RISK(i).Nn3,1),'DisplayName','CDI 3');
semilogy(S.Mw,median(S.RISK(i).Nn4,1),'DisplayName','CDI 4');
semilogy(S.Mw,median(S.RISK(i).Nn5,1),'DisplayName','CDI 5');
semilogy(S.Mw,median(S.RISK(i).Nn6,1),'DisplayName','CDI 6');
h=line(xlim(),M.N.T3*[1 1],'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
h=line(M.N.Tm*[1 1],ylim(), 'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Nuisance'); legend('Location','southeast');
%ylim(yl);
subplot(4,3,[8 11]);
semilogy(S.Mw,median(S.RISK(i).Nd1,1),'DisplayName','DS 1'); hold on;
semilogy(S.Mw,median(S.RISK(i).Nd2,1),'DisplayName','DS 2');
h=line(xlim(),M.D.T1*[1 1],'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
h=line(M.D.Tm*[1 1],ylim(), 'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Damage'); legend('Location','southeast');
%ylim(yl);
subplot(4,3,[9 12]);
semilogy(S.Mw,median(S.RISK(i).Pf1,1),'DisplayName','LPR'); hold on;
h=line(xlim(),M.R.T1*[1 1],'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
h=line(M.R.Tm*[1 1],ylim(), 'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Probability of Loss of Life'); title('LPR');
ylim([1e-7 1e0]);

% Plot the change in curves with proximity to the 'city.'
figure(4); clf;
subplot(311);
semilogy(S.Mw,median(S.RISK(m).Nn3,1),'-k','DisplayName','Farthest'); hold on;
semilogy(S.Mw,median(S.RISK(i).Nn3,1),'-b','DisplayName','Far');
semilogy(S.Mw,median(S.RISK(j).Nn3,1),'--b','DisplayName','Medium');
semilogy(S.Mw,median(S.RISK(k).Nn3,1),':b','DisplayName','Close');
semilogy(S.Mw,median(S.RISK(l).Nn3,1),':r','DisplayName','On-top');
h=line(xlim(),M.N.T3*[1 1],'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
h=line(M.N.Tm*[1 1],ylim(), 'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Nuisance (CDI 3)'); legend('Location','southeast');
subplot(312);
semilogy(S.Mw,median(S.RISK(m).Nd1,1),'-k','DisplayName','Farthest'); hold on;
semilogy(S.Mw,median(S.RISK(i).Nd1,1),'-b','DisplayName','Far');
semilogy(S.Mw,median(S.RISK(j).Nd1,1),'--b','DisplayName','Medium');
semilogy(S.Mw,median(S.RISK(k).Nd1,1),':b','DisplayName','Close');
semilogy(S.Mw,median(S.RISK(l).Nd1,1),':r','DisplayName','On-top');
h=line(xlim(),M.D.T1*[1 1],'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
h=line(M.D.Tm*[1 1],ylim(), 'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Number of Households Impacted'); title('Damage (DS 1)'); legend('Location','southeast');
subplot(313);
semilogy(S.Mw,median(S.RISK(m).Pf1,1),'-k','DisplayName','Farthest'); hold on;
semilogy(S.Mw,median(S.RISK(i).Pf1,1),'-b','DisplayName','Far');
semilogy(S.Mw,median(S.RISK(j).Pf1,1),'--b','DisplayName','Medium');
semilogy(S.Mw,median(S.RISK(k).Pf1,1),':b','DisplayName','Close');
semilogy(S.Mw,median(S.RISK(l).Pf1,1),':r','DisplayName','On-top');
h=line(xlim(),M.R.T1*[1 1],'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
h=line(M.R.Tm*[1 1],ylim(), 'Color',GREY,'LineStyle','--'); h.Annotation.LegendInformation.IconDisplayStyle = 'off';
xlabel('Red-Light Magnitdue (M_L)'); ylabel('Probability of Loss of Life'); title('LPR'); legend('Location','southeast');
ylim([1e-7 1e0]);

% Scatter plot nuisance vs damage counts.
figure(5); clf;
loglog(median(S.RISK(i).Nd1,1),median(S.RISK(i).Nn3,1),'o','DisplayName','CDI3-DS1'); hold on;
loglog(median(S.RISK(i).Nd2,1),median(S.RISK(i).Nn4,1),'o','DisplayName','CDI4-DS2');
%loglog(median(S.RISK(i).Nd3,1),median(S.RISK(i).Nn4,1),'o','DisplayName','CDI4-DS3');
%loglog(median(S.RISK(i).Nd4,1),median(S.RISK(i).Nn6,1),'o','DisplayName','CDI6-DS4');
ylabel('Nuisance Impact'); xlabel('Damage Impact'); legend('Location','southeast');

% Plot iso-maps
figure(6); clf;
subplot(3,6,1);
contourf(M.N.N3.lon,M.N.N3.lat,M.N.N3.Mr,linspace(ML_c(1),ML_c(2),35),'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title(['Iso-Nuisance Map, Nn3=',num2str(M.N.T3)]);
h = colorbar(); ylabel(h, 'Magnitude (M_L)');
colormap(gca,R_colormap('red-light')); caxis(ML_c);
xlim(XL); ylim(YL);
subplot(3,6,2);
contourf(M.N.N3.lon,M.N.N3.lat,M.N.N3.Nn,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title(['Iso-Magnitude Map, M_L=',num2str(M.N.Tm)]);
h = colorbar(); ylabel(h, 'Impacted Household Count');
colormap(gca,R_colormap('nuisance'));
xlim(XL); ylim(YL);
subplot(3,6,3);
contourf(M.N.N3.lon,M.N.N3.lat,M.N.N3.Nd,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Equivalent Damage Impact Map');
h = colorbar(); ylabel(h, 'Impacted Household Count');
colormap(gca,R_colormap('damage')); %caxis([0 100]);
xlim(XL); ylim(YL);
subplot(3,6,4);
contourf(M.N.N3.lon,M.N.N3.lat,M.N.N3.Nr,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Equivalent LPR Map');
h = colorbar(); ylabel(h, 'Probability of Loss of Life');
colormap(gca,R_colormap('LPR')); %caxis([0 100]);
xlim(XL); ylim(YL);
subplot(3,6,7);
contourf(M.D.D1.lon,M.D.D1.lat,M.D.D1.Mr,linspace(ML_c(1),ML_c(2),15),'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title(['Iso-Damage Map, Nd1=',num2str(M.D.T1)]);
h = colorbar(); ylabel(h, 'Magnitude (M_L)');
colormap(gca,R_colormap('red-light')); caxis(ML_c);
xlim(XL); ylim(YL);
subplot(3,6,8);
contourf(M.D.D1.lon,M.D.D1.lat,M.D.D1.Nd,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title(['Iso Magnitude Map, M_L=',num2str(M.D.Tm)]);
h = colorbar(); ylabel(h, 'Impacted Household Count');
colormap(gca,R_colormap('damage')); %caxis([0 100]);
xlim(XL); ylim(YL);
subplot(3,6,9);
contourf(M.D.D1.lon,M.D.D1.lat,M.D.D1.Nn,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Equivalent Nuisance Impact Map');
h = colorbar(); ylabel(h, 'Impacted Household Count');
colormap(gca,R_colormap('nuisance'));
xlim(XL); ylim(YL);
subplot(3,6,10);
contourf(M.D.D1.lon,M.D.D1.lat,M.D.D1.Nr,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Equivalent LPR Map');
h = colorbar(); ylabel(h, 'Probability of Loss of Life');
colormap(gca,R_colormap('LPR'));
xlim(XL); ylim(YL);
subplot(3,6,13);
contourf(M.R.R1.lon,M.R.R1.lat,M.R.R1.Mr,linspace(ML_c(1),ML_c(2),15),'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title(['Iso-LPR Map, Pf1=',num2str(M.R.T1)]);
h = colorbar(); ylabel(h, 'Magnitude (M_L)');
colormap(gca,R_colormap('red-light')); caxis(ML_c);
xlim(XL); ylim(YL);
subplot(3,6,14);
contourf(M.R.R1.lon,M.R.R1.lat,M.R.R1.Nr,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title(['Iso Magnitude Map, M_L=',num2str(M.R.Tm)]);
h = colorbar(); ylabel(h, 'Impacted Household Count');
colormap(gca,R_colormap('LPR')); %caxis([0 100]);
xlim(XL); ylim(YL);
subplot(3,6,15);
contourf(M.R.R1.lon,M.R.R1.lat,M.R.R1.Nn,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Equivalent Nuisance Impact Map');
h = colorbar(); ylabel(h, 'Impacted Household Count');
colormap(gca,R_colormap('nuisance'));
xlim(XL); ylim(YL);
subplot(3,6,16);
contourf(M.R.R1.lon,M.R.R1.lat,M.R.R1.Nd,'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Equivalent Damage Impact Map');
h = colorbar(); ylabel(h, 'Probability of Loss of Life');
colormap(gca,R_colormap('damage'));
xlim(XL); ylim(YL);

% Plot the combination map.
%figure(7); clf;
subplot(3,6,[5 6 11 12 17 18])
contourf(M.N.N3.lon,M.N.N3.lat,M.Mcomb,linspace(ML_c(1),ML_c(2),15),'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Combination Map');
h = colorbar(); ylabel(h, 'Magnitude (M_L)');
colormap(gca,R_colormap('red-light')); caxis(ML_c);
xlim(XL); ylim(YL);

% Plot some histograms of the iso-magnitude impacts.
figure(7); clf;
subplot(131);
histogram(M.N.N3.Nn(~isnan(M.N.N3.Nn)), round(sqrt(length(M.N.N3.Nn(~isnan(M.N.N3.Nn))))) ); hold on;
xlabel('Iso-Magnitude Nuisance Impacts'); ylabel('Counts');
set(gca, 'YScale', 'log');
plot(M.N.T3*[1 1],ylim,'--k');
subplot(132);
histogram(M.D.D1.Nd(~isnan(M.D.D1.Nd)), round(sqrt(length(M.D.D1.Nd(~isnan(M.D.D1.Nd))))) ); hold on;
xlabel('Iso-Magnitude Damage Impacts'); ylabel('Counts');
set(gca, 'YScale', 'log');
plot(M.D.T1*[1 1],ylim,'--k');
subplot(133);
histogram(M.R.R1.Nr(~isnan(M.R.R1.Nr)), round(sqrt(length(M.R.R1.Nr(~isnan(M.R.R1.Nr))))) ); hold on;
xlabel('Iso-Magnitude LPR'); ylabel('Counts');
set(gca, 'YScale', 'log');
plot(M.R.T1*[1 1],ylim,'--k');

% Plot the combination map damage/nuisance indicies.
figure(8); clf;
contourf(M.N.N3.lon,M.N.N3.lat,M.index+normrnd(0,0.01,size(M.index)),'LineColor','none'); hold on;
plot(S.MAP.lonB,S.MAP.latB,'-k');
plot(C1.X,C1.Y,'-r');
plot(C2.X,C2.Y,'-r');
xlabel('Longitude'); ylabel('Latitude'); title('Combination Map Indicies');
h = colorbar(); ylabel(h, 'Controlling Risk Index');
colormap(gca,R_colormap('indicies')); caxis([1 3]);
xlim(XL); ylim(YL);

% Output for DGSA.
%parameters=[S.dVAR.dM',S.dVAR.b',S.dVAR.dGM',S.dVAR.dF1',S.dVAR.dF2',S.dVAR.dSA',S.dVAR.dPOP',S.dVAR.dZ'];
%responsesN=[]; responsesD=[];
%for o=1:length(Rn.MAPs)
%    responsesN=[responsesN; Rn.MAPs(o).Mr(S.MAP.Ir)'];
%    responsesD=[responsesD; Rd.MAPs(o).Mr(S.MAP.Ir)'];
%end
%dlmwrite('/Users/rjs10/Desktop/Documents/courses/2020 Spring/GS260/SA/DGSA_Light-master/EF_TLP/Parameters.temp.txt',parameters);
%dlmwrite('/Users/rjs10/Desktop/Documents/courses/2020 Spring/GS260/SA/DGSA_Light-master/EF_TLP/ResponsesN.temp.txt', responsesN );
%dlmwrite('/Users/rjs10/Desktop/Documents/courses/2020 Spring/GS260/SA/DGSA_Light-master/EF_TLP/ResponsesD.temp.txt', responsesD );
